main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
	# Generic Views
	path('', views.landing, name='landing'),
	path('accounts/signup/', views.signup, name='signup'),
	path('accounts/type/', views.choose_type, name='choose_type'),
	# Hunter Views
	path('h/home', views.hunter_home, name='hunter_home'),
	path('h/prospect/<int:prospect>', views.hunter_view, name='hunter_view'),
	path('h/prospect/<int:prospect>/like', views.hunter_like, name='hunter_like'),
	path('h/prospect/<int:prospect>/dislike', views.hunter_dislike, name='hunter_dislike'),
	path('h/prospect/<int:prospect>/message', views.hunter_message, name='hunter_message'),
	# Prospect views
	path('p/home', views.prospect_home, name='prospect_home'),
	# Prospect Profile
	path('p/profile/create', views.prospect_add_profile, name='prospect_add_profile'),
	path('p/profile/edit', views.prospect_edit_profile, name='prospect_edit_profile'),
	# Prospect Education
	path('p/education/add', views.prospect_add_education, name='prospect_add_education'),
	path('p/education/edit/<int:education>', views.prospect_edit_education, name='prospect_edit_education'),
	path('p/education/remove/<int:education>', views.prospect_remove_education, name='prospect_remove_education'),
	# Prospect Experience
	path('p/experience/add', views.prospect_add_experience, name='prospect_add_experience'),
	path('p/experience/edit/<int:experience>', views.prospect_edit_experience, name='prospect_edit_experience'),
	path('p/experience/remove/<int:experience>', views.prospect_remove_experience, name='prospect_remove_experience'),
	# Prospect Snippets
	path('p/snippet/add', views.prospect_add_snippet, name='prospect_add_snippet'),
	path('p/snippet/edit/<int:snippet>', views.prospect_edit_snippet, name='prospect_edit_snippet'),
	path('p/snippet/remove/<int:snippet>', views.prospect_remove_snippet, name='prospect_remove_snippet')
]

myaceportrait/main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
	# Generic Views
	path('', views.landing, name='landing'),
	path('accounts/signup/', views.signup, name='signup'),
	path('accounts/type/', views.choose_type, name='choose_type'),
	# Hunter Views
	path('h/home', views.hunter_home, name='hunter_home'),
	path('h/prospect/<int:prospect>', views.hunter_view, name='hunter_view'),
	path('h/prospect/<int:prospect>/message', views.hunter_message, name='hunter_message'),
	# Prospect views
	path('p/home', views.prospect_home, name='prospect_home'),
	# Prospect Profile
	path('p/profile/create', views.prospect_add_profile, name='prospect_add_profile'),
	path('p/profile/edit', views.prospect_edit_profile, name='prospect_edit_profile'),
	# Prospect Education
	path('p/education/add', views.prospect_add_education, name='prospect_add_education'),
	path('p/education/edit/<int:education>', views.prospect_edit_education, name='prospect_edit_education'),
	path('p/education/remove/<int:education>', views.prospect_remove_education, name='prospect_remove_education'),
	# Prospect Experience
	path('p/experience/add', views.prospect_add_experience, name='prospect_add_experience'),
	path('p/experience/edit/<int:experience>', views.prospect_edit_experience, name='prospect_edit_experience'),
	path('p/experience/remove/<int:experience>', views.prospect_remove_experience, name='prospect_remove_experience'),
	# Prospect Snippets
	path('p/snippet/add', views.prospect_add_snippet, name='prospect_add_snippet'),
	path('p/snippet/edit/<int:snippet>', views.prospect_edit_snippet, name='prospect_edit_snippet'),
	path('p/snippet/remove/<int:snippet>', views.prospect_remove_snippet, name='prospect_remove_snippet')
]

myaceportrait/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

from django.contrib.auth.models import User

#Only definition of prospect methods is required since there is no capacity of hunters to edit db entries

# Differentiation of hunter vs prospect user type.
class UserProfile(models.Model):
	TYPE = (
		('HUNTER', 'Hunter'),
		('PROSPECT', 'Prospect')
	)

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	user_type = models.CharField(max_length=250, choices=TYPE)
	
	def __str__(self):
		return "%s (%s)" % (self.user.username, self.user_type)


#Included definition of database saved variable per prospect user object
class ProspectProfile(models.Model):
	prospect = models.OneToOneField(User, on_delete=models.CASCADE)
	github = models.CharField(max_length=100, blank=True, null=True)
	bio = models.CharField(max_length=10000, blank=True, null=True)
	skills = models.CharField(max_length=10000, blank=True, null=True)
	likes = models.ManyToManyField(User, related_name="likes")

	def __str__(self):
		return self.prospect.username

	@property
	def total_likes(self):
		return "%s" % (self.likes.count())

#Same as above for code example
class ProspectCodeSnippet(models.Model):
	prospect = models.ForeignKey(User, on_delete=models.CASCADE)
	date_created = models.DateTimeField(auto_now_add=True)
	snippet_name = models.CharField(max_length=100)
	snippet_code = models.CharField(max_length=10000)

	def __str__(self):
		return "%s: %s" % (self.prospect.username, self.snippet_name)

#See above
class ProspectEducation(models.Model):
	TYPE = (
		('C', 'Certificate'),
		('D', 'Diploma'),
		('B', 'Bachelors'),
		('M', 'Masters'),
		('P', 'PhD')
	)

	prospect = models.ForeignKey(User, on_delete=models.CASCADE)
	date_created = models.DateTimeField(auto_now_add=True)
	institution = models.CharField(max_length=100)
	edu_type = models.CharField(max_length=100, choices=TYPE)
	edu_subject = models.CharField(max_length=100)
	start_date = models.DateField()
	end_date = models.DateField()

	def __str__(self):
		return "%s, (%s, %s in %s)" % (self.prospect.username, self.institution, self.edu_type, self.edu_subject)

#See above	
class ProspectExperience(models.Model):
	TYPE = (
		('W', 'Work'),
		('I', 'Internship'),
		('V', 'Volunteer')
	)

	prospect = models.ForeignKey(User, on_delete=models.CASCADE)
	date_created = models.DateTimeField(auto_now_add=True)
	position = models.CharField(max_length=100)
	work_type = models.CharField(max_length=20, choices=TYPE)
	name = models.CharField(max_length=250)
	location = models.CharField(max_length=250)
	start_date = models.DateField()
	end_date = models.DateField()

	def __str__(self):
		return "%s, (%s in %s, %s)" % (self.prospect.username, self.name, self.location, self.work_type)

main/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.mail import send_mail

from main.models import *
from main.forms import *

#Call to included Django user verification control method
def is_classified(request):
	if not UserProfile.objects.get(user=request.user):
		return redirect('choose_type')

#Defined hunter vs prospect control function defined to guarantee prospects cannot see what hunters should see	
def is_hunter(request):
	profile = UserProfile.objects.get(user=request.user)
	user_type = profile.user_type
	if user_type == 'HUNTER':
		return True
	else:
		return False

#Call to generate typical landing page
def landing(request):
	if request.user.is_authenticated:
		try:
			UserProfile.objects.get(user=request.user)
		except UserProfile.DoesNotExist:
			return redirect ('choose_type')
		if is_hunter(request):
			return redirect('hunter_home')
		else:
			return redirect('prospect_home')
	else:
		return render(request, 'main/landing.html')

#Call to verify that user type allow for appropriate redirect
def choose_type(request):
	if request.user.is_authenticated:
		context = {"pass": "pass"}
		if request.method == 'POST':
			form = UserProfileForm(request.POST)
			if form.is_valid():
				form = form.save(commit=False)
				form.user = request.user
				form.save()
				return redirect('landing')
		else:
			form = UserProfileForm()
		context = {
			'form': form
		}
		return render(request, 'registration/choose_type.html', context)
	return redirect('landing')

#Call to render appropriate signup response
def signup(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/accounts/login')
	else:
		form = RegistrationForm()
	context = {
		'form': form
	}
	return render(request, 'registration/signup.html', context)


# Hunter Views
def hunter_home(request):
	search_term=''
	if request.user.is_authenticated:
		context = {"pass": "pass"}
		is_classified(request)
		if is_hunter(request):
			prospects = UserProfile.objects.filter(user_type="PROSPECT")
			prospect_profiles = ProspectProfile.objects.all()
			if 'search' in request.GET:
				search_term = request.GET['search']
				if search_term != '':
					prospect_profiles = ProspectProfile.objects.filter(Q(prospect__username__icontains=search_term) 
						| Q(bio__icontains=search_term) | Q(skills__icontains=search_term))
			else:
				prospect_profiles = ProspectProfile.objects.all()

			context = {
				'prospects': prospects,
				'prospect_profiles': prospect_profiles,
				'search_term': search_term
			}
		return render(request, 'main/hunter/home.html', context)
	return redirect('landing')

#Addition of hunter like functionality
def hunter_like(request, prospect):
	search_term=''
	if request.user.is_authenticated:
		context = {"pass": "pass"}
		is_classified(request)
		if is_hunter(request):
			if request.method == 'POST':
				hunter = request.user.id
				prospectuser = User.objects.get(pk=prospect)
				prospect = ProspectProfile.objects.get(prospect=prospectuser)

				if prospect.likes.filter(pk=hunter).exists() == False:
					prospect.likes.add(hunter)
					prospect.save()
			prospects = UserProfile.objects.filter(user_type="PROSPECT")
			context = {
				'prospects': prospects
			}
			return redirect('hunter_home')
		return render(request, 'main/hunter/home.html', context)
	return redirect('hunter_home')

#Removal of a provided like by hunter to prospect
def hunter_dislike(request, prospect):
	if request.user.is_authenticated:
		context = {"pass": "pass"}		
		is_classified(request)
		if is_hunter(request):
			if request.method == 'POST':
				hunter = request.user.id
				prospectuser = User.objects.get(pk=prospect)
				prospect = ProspectProfile.objects.get(prospect=prospectuser)

				if prospect.likes.filter(pk=hunter).exists():
					prospect.likes.remove(hunter)
					prospect.save()
		
			prospects = UserProfile.objects.filter(user_type="PROSPECT")
			context = {
				'prospects': prospects
			}
			return redirect('hunter_home')
		return render(request, 'main/hunter/home.html', context)
	return redirect('landing')

#General hunter initial home view
def hunter_view(request, prospect=None):
	if request.user.is_authenticated:
		context = {"pass": "pass"}
		is_classified(request)
		if is_hunter(request):
			user = User.objects.get(pk=prospect)
			prospect = ProspectProfile.objects.get(prospect=user)
			education = ProspectEducation.objects.filter(prospect=user)
			experience = ProspectExperience.objects.filter(prospect=user)
			snippets = ProspectCodeSnippet.objects.filter(prospect=user)
			context = {
				'prospect': prospect,
				'education': education,
				'experience': experience,
				'snippets': snippets
			}
		return render(request, 'main/hunter/prospect.html', context)
	return redirect('landing')

#Allows for smtp request of hunter to prospect
def hunter_message(request, prospect=None):
	if request.user.is_authenticated:
		context = {"pass": "pass"}
		is_classified(request)
		if is_hunter(request):
			if request.method == "POST":
				form = ContactForm(request.POST)
				if form.is_valid():
					data = form.cleaned_data
					
					subject = 'myACEportrait - Message from '+str(request.user.username)
					message = data['message']
					from_email = str(request.user.email)
					prospect = User.objects.get(pk=prospect)
					recipients = [prospect.email]
					
					send_mail(subject, message, from_email, recipients, fail_silently=False)
					return redirect('hunter_home')
			else:
				form = ContactForm()
			context = {
				'form': form
			}
			return render(request, 'main/hunter/send_mail.html', context)

# Prospect Views
def prospect_home(request):
	if request.user.is_authenticated:
		is_classified(request)
		if not is_hunter(request):
			try:
				profile = ProspectProfile.objects.get(prospect=request.user)
			except ProspectProfile.DoesNotExist:
				return redirect('/p/profile/create')
			snippets = ProspectCodeSnippet.objects.filter(prospect=request.user).order_by('-date_created')
			education = ProspectEducation.objects.filter(prospect=request.user).order_by('-date_created')
			experience = ProspectExperience.objects.filter(prospect=request.user).order_by('-date_created')
			context = {
				'profile': profile,
				'snippets': snippets,
				'education': education,
				'experience': experience
			}
			return render(request, 'main/prospect/home.html', context)
	return redirect('landing')

#New prospect request to add profile
def prospect_add_profile(request):
	if request.user.is_authenticated:
		is_classified(request)
		if not is_hunter(request):
			if request.method == 'POST':
				form = ProspectProfileForm(request.POST)
				if form.is_valid():
					form = form.save(commit=False)
					form.prospect = request.user
					form.save()
					return redirect('prospect_home')
			else:
				form = ProspectProfileForm()
			context = {
				'form': form
			}
			return render(request, 'main/prospect/add_profile.html', context)
	return redirect('landing')

#Prospect altering of existing saved profile config, alters database of conatined propsect user data
def prospect_edit_profile(request):
	if request.user.is_authenticated:
		is_classified(request)
		if not is_hunter(request):
			profile = ProspectProfile.objects.get(prospect=request.user)
			if request.method == 'POST':
				form = ProspectProfileForm(request.POST, instance=profile)
				if form.is_valid():
					form.save()
					return redirect('prospect_home')
			else:
				form = ProspectProfileForm(instance=profile)
			context =  {
				'form': form
			}
			return render(request, 'main/prospect/add_profile.html', context)

#Allow prospect to add example of produced code
def prospect_add_snippet(request):
	if request.user.is_authenticated:
		is_classified(request)
		if not is_hunter(request):
			if request.method == 'POST':
				form = ProspectCodeSnippetForm(request.POST)
				if form.is_valid():
					form = form.save(commit=False)
					form.prospect = request.user
					form.save()
					return redirect('prospect_home')
			else:
				form = ProspectCodeSnippetForm()
			context = {
				'form': form
			}
			return render(request, 'main/prospect/add_snippet.html', context)
	return redirect('landing')

#Allow prospect to edit exitsing snippet saved to db
def prospect_edit_snippet(request, snippet=None):
	if request.user.is_authenticated:
		is_classified(request)
		if not is_hunter(request):
			snippet = ProspectCodeSnippet.objects.get(pk=snippet)
			if snippet.prospect == request.user:
				if request.method == 'POST':
					form = ProspectCodeSnippetForm(request.POST, instance=snippet)
					if form.is_valid():
						form.save()
						return redirect('prospect_home')
				else:
					form = ProspectCodeSnippetForm(instance=snippet)
				context = {
					'form': form
				}
				return render(request, 'main/prospect/add_snippet.html', context)
	return redirect('landing')

#Bye bye snippet
def prospect_remove_snippet(request, snippet=None):
	if request.user.is_authenticated:
		is_classified(request)
		snippet = ProspectCodeSnippet.objects.get(pk=snippet)
		if snippet.prospect == request.user:
			snippet.delete()
			#ProspectCodeSnippet.objects.get(pk=snippet).delete()
		return redirect('prospect_home')
	return redirect('landing')

#See above
def prospect_add_education(request):
	if request.user.is_authenticated:
		is_classified(request)
		if not is_hunter(request):
			if request.method == 'POST':
				form = ProspectEducationForm(request.POST)
				if form.is_valid():
					form = form.save(commit=False)
					form.prospect = request.user

main/templates/main/prospect/add_education.html
{% include 'main/components/header.html' %}
{% load static %}
{% include 'main/components/hunter-navbar.html' %}
<style>
body {background-color: white;
	  background-image: url({% static 'img/bg-pattern.png' %});}
</style>
<div class="container my-3 h-75">
	<div class="row">
		<div class="col-12" style="background-color: white">
			<h3>Education</h3>
			<form method="POST">
				{% csrf_token %}
				{{ form.non_field_errors }}
				<div class="form-group form-row">
					<label class="col-4">Institution Name</label>
					{{ form.institution }}
					{{ form.institution.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Education Received</label>
					{{ form.edu_type }}
					{{ form.edu_type.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Education Subject</label>
					{{ form.edu_subject }}
					{{ form.edu_subject.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Start Date</label>
					{{ form.start_date }}
					{{ form.start_date.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">End Date</label>
					{{ form.end_date }}
					{{ form.end_date.errors }}
				</div>
				<button type="submit" class="btn btn-dark text-light w-100">Submit</button>
			</form>
		</div>
	</div>
</div>

main/templates/main/prospect/add_experience.html
{% include 'main/components/header.html' %}
{% load static %}
{% include 'main/components/hunter-navbar.html' %}
<style>
body {background-color: white;
	  background-image: url({% static 'img/bg-pattern.png' %});}
</style>
<div class="container my-3 h-75">
	<div class="row">
		<div class="col-12" style="background-color: white">
			<h3>Experience</h3>
			<form method="POST">
				{% csrf_token %}
				{{ form.non_field_errors }}
				<div class="form-group form-row">
					<label class="col-4">Organization Name</label>
					{{ form.name }}
					{{ form.name.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Experience Type</label>
					{{ form.work_type }}
					{{ form.work_type.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Position</label>
					{{ form.position }}
					{{ form.position.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Location</label>
					{{ form.location }}
					{{ form.location.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Start Date</label>
					{{ form.start_date }}
					{{ form.start_date.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">End Date</label>
					{{ form.end_date }}
					{{ form.end_date.errors }}
				</div>
				<button type="submit" class="btn btn-dark text-light w-100">Submit</button>
			</form>
		</div>
	</div>
</div>

main/templates/main/prospect/add_profile.html
{% include 'main/components/header.html' %}
{% load static %}
{% include 'main/components/hunter-navbar.html' %}
<style>
body {background-color: white;
	  background-image: url({% static 'img/bg-pattern.png' %});}
</style>
<div class="container my-3 h-75">
	<div class="row">
		<div class="col-12" style="background-color: white">
			<form method="POST">
				{% csrf_token %}
				{{ form.non_field_errors }}
				<div class="form-group form-row">
					<label class="col-4">Github/Portfolio Link</label>
					{{ form.github }}
					{{ form.github.errors }}	
				</div>
				<div class="form-group form-row">
					<label class="col-4">Bio</label>
					{{ form.bio }}
					{{ form.bio.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Skills</label>
					{{ form.skills }}
					{{ form.skills.errors }}
				</div>
				<button class="btn btn-dark text-light w-100">Submit</button>
			</form>
		</div>
	</div>
</div>

main/templates/main/prospect/add_snippet.html
{% include 'main/components/header.html' %}
{% load static %}
{% include 'main/components/hunter-navbar.html' %}
<style>
body {background-color: white;
	  background-image: url({% static 'img/bg-pattern.png' %});}
</style>
<div class="container my-3 h-75">
	<div class="row">
		<div class="col-12" style="background-color: white">
			<h3>Code Snippet</h3>
			<form method="POST">
				{% csrf_token %}
				{{ form.non_field_errors }}
				<div class="form-group form-row">
					<label class="col-4">Name</label>
					{{ form.snippet_name }}
					{{ form.snippet_name.errors }}
				</div>
				<div class="form-group form-row">
					<label class="col-4">Code</label>
					{{ form.snippet_code }}
					{{ form.snippet_code.errors }}
				</div>
				<button type="submit" class="btn btn-dark text-light w-100">Submit</button>
			</form>
		</div>
	</div>
</div>

main/templates/main/prospect/home.html
{% include 'main/components/header.html' %}
{% load static %}
{% include 'main/components/hunter-navbar.html' %}
<style>
body {background-color: white;
	  background-image: url({% static 'img/bg-pattern.png' %});}
</style>
<div class="container my-3 h-75">
	<div class="row">
		<div class="col-lg-12" style="background-color: white">
			<h3>Prospect Bio</h3>
			<table class="table table-hover">
				<tr>
					<th>Prospect Name</th>
					<td>{{ profile.prospect.username }}</td>
				</tr>
				<tr>
					<th>Prospect Email</th>
					<td>{{ profile.prospect.email }}
				</tr>
				<tr>
					<th>Prospect Bio</th>
					<td><p>{{ profile.bio }}</p></td>
				<tr>
				</tr>
					<th>Prospect Skills</th>
					<td><p>{{ profile.skills }}</p></td>
				</tr>
				<tr>
					<th>Prospect Github</th>
					<td>{{ profile.github }}</td>
				</tr>
				<tr>
					<th>Prospect Likes</th>
					<td>{{ profile.total_likes }}</td>
				</tr>
				<tr>

				</tr>
			</table>

			<a class="btn btn-dark text-light my-3" href="/p/profile/edit">Edit Profile</a>

			<h3>Education</h3>
			{% if education %}
				{% for edu in education %}
			<table class="table table-hover">
				<tr>
					<th>Institution</th>
					<td>{{ edu.institution }}</td>
				</tr>
				<tr>
					<th>Program</th>
					<td>{{ edu.get_edu_type_display }} in {{ edu.edu_subject }}
				</tr>
				<tr>
					<th>Start Date - End Date</th>
					<td>{{ edu.start_date }} - {{ edu.end_date }}</td>
				</tr>
			</table>
			<a class="btn btn-dark text-light my-3" href="/p/snippet/edit/{{ edu.pk }}">Edit {{ edu.institution }}</a>
			<a class="btn btn-danger text-light my-3" href="/p/snippet/remove/{{ edu.pk }}">Remove {{ edu.institution }}</a>
				{% endfor %}
			{% else %}
			<p>No Education has been added to this profile.</p>
			{% endif %}

			<br><a class="btn btn-dark text-light my-3" href="/p/education/add">Add Education</a>

			<h3>Experience</h3>
			{% if experience %}
				{% for exp in experience %}
			<table class="table table-hover">
				<tr>
					<th>Organization</th>
					<td>{{ exp.name }}</td>
				</tr>
				<tr>
					<th>Type</th>
					<td>{{ exp.get_work_type_display }}</td>
				</tr>
				<tr>
					<th>Position</th>
					<td>{{ exp.position }}</td>
				</tr>
				<tr>
					<th>Location</th>
					<td>{{ exp.location }}</td>
				</tr>
				<tr>
					<th>Start Date - End Date</th>
					<td>{{ exp.start_date }} - {{ exp.end_date }}</td>
				</tr>
			</table>
			<a class="btn btn-dark text-light my-3" href="/p/snippet/edit/{{ exp.pk }}">Edit {{ exp.name }}</a>
			<a class="btn btn-danger text-light my-3" href="/p/snippet/remove/{{ exp.pk }}">Remove {{ exp.name }}</a>
				{% endfor %}
			{% else %}
			<p>No Experience has been added to this profile.</p>
			{% endif %}

			<br><a class="btn btn-dark text-light my-3" href="/p/experience/add">Add Experience</a>

			<h3>Code Snippets</h3>
			{% if snippets %}
				{% for snippet in snippets %}
			<table class="table table-hover">
				<tr>
					<th>{{ snippet.snippet_name }}</th>
				</tr>
				<tr>
					<td style="white-space:pre">{{ snippet.snippet_code }}</td>
				</tr>
			</table>
			<a class="btn btn-dark text-light my-3" href="/p/snippet/edit/{{ snippet.pk }}">Edit {{ snippet.snippet_name }}</a>
			<a class="btn btn-danger text-light my-3" href="/p/snippet/remove/{{ snippet.pk }}">Remove {{ snippet.snippet_name }}</a>
				{% endfor %}
			{% else %}
			<p>No Code Snippets have been added to this profile.</p>
			{% endif %}

			<br><a class="btn btn-dark text-light my-3" href="/p/snippet/add">Add Code Snippet</a>
		</div>
	</div>
</div>